name: Deploy
on: 
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server
          password: ${{secrets.SSH_PASSWORD}} # User password

          script: |
            ./deploy_test.sh ${{secrets.NODE_ENV}} ${{secrets.PORT}} ${{secrets.DB_USER}} ${{secrets.DB_PASSWORD}} ${{secrets.DB_HOST}} ${{secrets.DB_NAME}} ${{secrets.DB_PORT}}
