name: Deploy
on: 
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server
          password: ${{secrets.SSH_PASSWORD}} # User password

          script: |
            cd /var/www || exit
            pm2 stop deploy-test
            pm2 delete deploy-test
            if [[ -d "/var/www/test/deploy-test" ]]; then
              echo "Directory $pathMainDir exists"
              cd test/deploy-test/ || exit
              git pull origin main
              echo "Deployment succesful"
              npm install
              echo -e "NODE_ENV=${{secrets.NODE_ENV}}\nPORT=${{secrets.PORT}}\nDB_USER=${{secrets.DB_USER}}\nDB_PASSWORD=${{secrets.DB_PASSWORD}}\nDB_HOST=${{secrets.DB_HOST}}\nDB_NAME=${{secrets.DB_NAME}}\nDB_PORT=${{secrets.DB_PORT}}" > .env
              pm2 start index.js --name deploy-test
              if [[ migrations -gt $(find /var/www/test/deploy-test/src/db/migrations | wc -l) ]]; then
                npm run migrations:run
              fi
            fi
