name: Deploy
on: 
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server
          password: ${{secrets.SSH_PASSWORD}} # User password

          script: |
            cd /var/www
            pm2 stop deploy-test
            pm2 delete deploy-test
            rm -rf test
            mkdir test
            cd test
            git clone git@github.com:Sharmaz/deploy-test.git
            echo 'Deployment succesful'
            cd deploy-test
            npm install
            NODE_ENV=${{secrets.NODE_ENV}} PORT=${{secrets.PORT}} pm2 start index.js --name deploy-test
